### ISSUE TITLE
caching issues

### ISSUE THREAD

**Issue by Merovius** [nnev/c14h#1]
Wenn man eine chaotische Viertelstunde einträgt, wird diese erst nach einem forced-reload in der Liste angezeigt (wenn man diese vorher angebraust hat natürlich). Das ist irgendwie blöd. Da scheint irgendwo ein aggressiver cache zu sein (vielleicht aber auch bei mir).

**Comment by stapelberg** [comment]
Fixed durch e66e57cb58803be2b1351ff12d2d0de797bd9e6f in eris:/srv/git/website
