### ISSUE TITLE
Remove Date of entry

### ISSUE THREAD

**Issue by Merovius** [nnev/c14h#3]
We need to be able to delete the date (set it back to "TBA") from the website.

**Comment by koebi** [comment]
why do we even distinguish between an empty and a non-empty date when updating?
What was the original idea behind this?

**Comment by Merovius** [comment]
Probably precisely this. As I said, this is probably already intended to be possible, but buggy. The fix is probably (now that I look at the code) to add a 'date = NULL' into the sql statement at https://github.com/nnev/c14h/blob/master/sql.go#L50

**Comment by koebi** [comment]
yeah, thougth so, and to me it looks like it is. fix incoming
