### ISSUE TITLE
Anti-Spam

### ISSUE THREAD

**Issue by Merovius** [nnev/c14h#6]
Wir müssen uns irgendwas wegen Spam überlegen. Sinnvoll wäre z.B., frank Änderungen in den Channel posten zu lassen, dafür ist die Spam-Frequenz bisher gering genug und das ist sowieso schön.

**Comment by Merovius** [comment]
http://blog.codinghorror.com/captcha-is-dead-long-live-captcha/ is also attractive

**Comment by Merovius** [comment]
Okay, should read first. He doesn't actually describes the technique. Basically, he rolled out a captcha that served a static image containing the word "orange". It's basically free and uncomplicated to build, but as long as no sophisticated or specialized bot turns up it might suffice.

**Comment by breunigs** [comment]
what about adding a password field and sharing that password un person / via personal mail? 

the only difficulty i see here is when people are asking over the mailing list. the password should be something simple like "noname" that is easy to remember.
